services:
  converter:
    build: converter
    ports:
      - "8020:8080"
    volumes:
      - ~/Downloads/Conversions:/Conversions:rw
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
